#配置端口号
server:
  port: 8090

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_fyk?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true #其实是之前的openEntityManagerInViewInterceptor，解决在Spring MVC与JPA之间Session的声明周期问题
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      prefix: /
#      suffix: .html
  resources:
    static-locations: classpath:/static
logging:
  level:
    com:
      javaweb:
        controller: debug
        global:
          exception: warn




